apiVersion: apps/v1
kind: Deployment
metadata:
  name: acopio
  labels:
    app: acopio
spec:
  selector:
    matchLabels:
      app: acopio
  replicas: 2
  template:
    metadata:
      labels:
        app: acopio
    spec:
      containers:
      - name: acopio
        image: nicolascuitino4/backend-acopio:latest
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://config-service:8081
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://eureka-service:8761
        - name: eureka.instance.preferIpAddress
          value: "true"
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: postgresql-acopio-db
              key: host
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: postgresql-acopio-db
              key: POSTGRESQL_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: postgres_username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: postgres_password
---
apiVersion: v1
kind: Service
metadata:
  name: acopio
  labels:
    app: acopio
spec:
  selector:
    app: acopio
  ports:
    - nodePort: 30501
      protocol: TCP
      port: 8083
      targetPort: 8083
  type: NodePort