server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: proveedores
          uri: lb://proveedores
          predicates:
            - Path=/proveedor/**
        - id: acopio
          uri: lb://acopio
          predicates:
            - Path=/acopio/**
        - id: GyST
          uri: lb://GyST
          predicates:
            - Path=/details/**
        - id: pagos
          uri: lb://pagos
          predicates:
            - Path=/pagos/**